services:
  - type: web
    name: sai-infotech-ecommerce
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sai-infotech-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: VITE_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: VITE_CLOUDINARY_UPLOAD_PRESET
        sync: false
    healthCheckPath: /api/health

databases:
  - name: sai-infotech-db
    databaseName: sai_infotech
    user: sai_infotech_user
    plan: starter